// audio
const RESET_PLAYER = 'RESET_PLAYER';
const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
const SET_IS_PLAYING = 'SET_IS_PLAYING';
const CLEAR_QUEUE = 'CLEAR_QUEUE';
const ENQUEUE = 'ENQUEUE';
const DEQUEUE = 'DEQUEUE'

// feed
const SET_FEED = 'SET_FEED';
const PAGINATE_FEED = 'PAGINATE_FEED';
const SET_CURRENT_FEED = 'SET_CURRENT_FEED';
const SET_CURRENT_FEED_INDEX = 'SET_CURRENT_FEED_INDEX';
const INC_CURRENT_FEED_INDEX = 'INC_CURRENT_FEED_INDEX';

export { 
  RESET_PLAYER,
  SET_CURRENT_TRACK, 
  SET_IS_PLAYING,
  CLEAR_QUEUE,
  ENQUEUE,
  DEQUEUE,
  SET_FEED,
  PAGINATE_FEED,
  SET_CURRENT_FEED,
  SET_CURRENT_FEED_INDEX,
  INC_CURRENT_FEED_INDEX
}