const RESET_PLAYER = 'RESET_PLAYER';
const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
const SET_IS_PLAYING = 'SET_IS_PLAYING';
const CLEAR_QUEUE = 'CLEAR_QUEUE';
const ENQUEUE = 'ENQUEUE';
const DEQUEUE = 'DEQUEUE'

export { 
  RESET_PLAYER,
  SET_CURRENT_TRACK, 
  SET_IS_PLAYING,
  CLEAR_QUEUE,
  ENQUEUE,
  DEQUEUE
};